apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tushare.fullname" . }}
  labels:
    {{- include "tushare.labels" . | nindent 4 }}
data:
  mysql-database: {{ .Values.mysql.database | quote }}
  mysql-user: {{ .Values.mysql.user | quote }}
