{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tushare.mysql.fullname" . }}
  labels:
    {{- include "tushare.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    {{- include "tushare.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
{{- end }}
