apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tushare.fullname" . }}
  labels:
    {{- include "tushare.labels" . | nindent 4 }}
type: Opaque
data:
  tushare-token: {{ .Values.tushareToken | b64enc | quote }}
  mysql-root-password: {{ .Values.mysql.rootPassword | b64enc | quote }}
  mysql-password: {{ .Values.mysql.password | b64enc | quote }}
